<?php
/**
 * @file
 * transactworld module for Drupal Commerce.
 */

/**
 * Administration forms form payment method.
 */
function commerce_transactworld_settings_form($settings = NULL) {
  $form = array();
  $settings = (array) $settings + array(
   // 'totype' => '',
    'toid' => '',
	'partenerid' => '',
	'ipaddr' => '',
    'pctype' => '',
    'paymenttype' => '',
    'cardtype' => '',
    'reservedField1' => '',
    'reservedField2' => '',
    'working_key' => '',
    'totype' => '',
    'test_url' => '',
    'live_url' => '',
    'transactworld_server' => '',
	
  );

  $form['toid'] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant id'),
    '#default_value' => $settings['toid'],
    '#required' => TRUE,
  );
  
  
  $form['partenerid'] = array(
    '#type' => 'textfield',
    '#title' => t('Partner id'),
    '#default_value' => $settings['partenerid'],
    '#required' => TRUE,
  );
  
  $form['ipaddr'] = array(
    '#type' => 'textfield',
    '#title' => t('Ip address id'),
    '#default_value' => $settings['ipaddr'],
    '#required' => TRUE,
  );
  

  $form['working_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Working key'),
    '#default_value' => $settings['working_key'],
    '#required' => TRUE,
  );

  $form['totype'] = array(
    '#type' => 'textfield',
    '#title' => t('Partner Name'), 
    '#default_value' => $settings['totype'],
    '#required' => TRUE,
  );

  $form['transactworld_server'] = array(
    '#type' => 'select',
    '#title' => t('Payment Mode'),
    '#description' => t('The Available list of transactworld Servers'),
    '#options' => array(
	  $settings['live_url'] => ('Live'),
	  $settings['test_url'] => ('Test'),
	 ),
    '#default_value' => $settings['transactworld_server'],
  );
  
  $form['test_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Test url'), 
    '#default_value' => $settings['test_url'],
    '#required' => TRUE,
  );
  
  $form['live_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Live url'), 
    '#default_value' => $settings['live_url'],
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Register payment mehtod.
 */
function commerce_transactworld_commerce_payment_method_info() {
  $icon = _commerce_transactworld_icons();
  $display_title = t('TransactWorld'); 
  $payment_methods = array();
  $payment_methods['commerce_transactworld'] = array(
    'title' => t("Pay securely with transactworld"), 
    'display_title' => $display_title,
    'short_title' => 'transactworld',
    'description' => t("Payment method for transactworld"),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );
  return $payment_methods;
}

/**
 * Ask for transactworld redirect form.
 */
function commerce_transactworld_redirect_form($form, $form_state, $order, $payment_method){
  
  $wrapper = entity_metadata_wrapper('commerce_order', $order);   
  $billing_address = $wrapper->commerce_customer_billing->commerce_customer_address->value(); // print_r($billing_address); exit;
  // Get financial info.
  $currency_code = $wrapper->commerce_order_total->currency_code->value();
  
  // billing address starts here 
  $order_data = array(
    'amount' => $wrapper->commerce_order_total->amount->value() / 100,
    'order_id' => $order->order_id,
    'cancel_url' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
    'redirect_url' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
    'working_key' => $payment_method['settings']['working_key'],
    'language' => 'EN',
    'currency' => $currency_code,
    'billing_name' => $billing_address['name_line'],
    'billing_address' => $billing_address['thoroughfare']. ' ' . $billing_address['premise'] . ' ' . $billing_address['sub_premise'],
    'billing_zip' => $billing_address['postal_code'],
    'billing_city' => $billing_address['locality'],
    'billing_state' => $billing_address['administrative_area'],
    'billing_country' => $billing_address['country'],
  );
  
 $form['totype'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'totype'),
  	'#value' => $payment_method['settings']['totype'],
  );
 
  $form['toid'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'toid'),
  	'#value' => $payment_method['settings']['toid'],
  );
  
  
   $form['partenerid'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'partenerid'),
  	'#value' => $payment_method['settings']['partenerid'],
  );
  
  
   $form['ipaddr'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'ipaddr'),
  	'#value' => $payment_method['settings']['ipaddr'],
  );
  
  
  $form['pctype'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'pctype'),
  	'#value' => '1_1|1_2',
  );
  
  
   $form['amount'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'amount'),
  	'#value' => number_format((float)$wrapper->commerce_order_total->amount->value() / 100, 2, '.', ''),
  );
  $form['description'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'description'),
  	'#value' => $order->order_id,
  ); 
  $form['redirecturl'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'redirecturl'),
  	'#value' =>url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
  );  
  
  
  // Address fields starts here 
$form['TMPL_street'] = array(
'#type' => 'hidden',
'#value' => $billing_address['thoroughfare']. ' ' . $billing_address['premise'] . ' ' . $billing_address['sub_premise'],
);
$form['TMPL_COUNTRY'] = array(
'#type' => 'hidden',
'#value' => $billing_address['country'], 
);

$form['TMPL_state'] = array(
'#type' => 'hidden',
'#value' => $billing_address['administrative_area'],
);
$form['TMPL_city'] = array(
'#type' => 'hidden',
'#value' => $billing_address['locality'],
);
$form['TMPL_zip'] = array(
'#type' => 'hidden',
'#value' => $billing_address['postal_code'],
);
  
  // Address fields ends here 
  
  $checksum = MD5(trim($payment_method['settings']['toid']) . "|" . trim( $payment_method['settings']['totype']) . "|" . trim(number_format((float)$wrapper->commerce_order_total->amount->value() / 100, 2, '.', '')) . "|" . trim($order->order_id) . "|" .url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)). "|" . trim($payment_method['settings']['working_key']));
  $form['checksum'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'checksum'),
  	'#value' =>$checksum,
  );
  $form['TMPL_CURRENCY'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'TMPL_CURRENCY'),
  	'#value' =>'USD',
  );
  $form['TMPL_AMOUNT'] = array(
  	'#type' => 'hidden',
  	'#attributes' => array('name' => 'TMPL_AMOUNT'),
  	'#value' =>$wrapper->commerce_order_total->amount->value() / 100,
  );  
  
 
  $form['#action'] = $payment_method['settings']['transactworld_server'];
  return $form;  
}



/**
 * Implements hook_redirect_form_validate().
 */


function commerce_transactworld_redirect_form_validate($order, $payment_method) {
  $working_key = $payment_method['settings']['working_key'];
  
  // This is the response sent by the transactworld Server.
  $trackingId = $_REQUEST["trackingid"];
  $desc = $_REQUEST["desc"];
  $amount = $_REQUEST["amount"];
  $status = $_REQUEST["status"];
  $message = t('Security error ip Address was: @ip', array('@ip' => ip_address()));
  if ($status === "Y") {
    commerce_transactworld_transaction($order, $payment_method, $status);
    commerce_order_status_update($order, 'processing');
    return drupal_set_message(t('Thank you for shopping with us. Your account has been charged and your transaction is successful.'));
    
    // Here you need to put in the routines for a successful.
    // Transaction such as sending an email to customer.
    // Setting database status, informing logistics etc etc.
  }
  elseif ($status === "P") {
    commerce_transactworld_transaction($order, $payment_method, $status);
    commerce_order_status_update($order, 'pending');
    return drupal_set_message(('Thank you for shopping with us.We will keep you posted regarding the status of your order through e-mail'));
    // This is for payment American Express Card payment only.
    // American Express authorisation status is available only after 5-6.
  }
  elseif ($status === "N") {
    commerce_transactworld_transaction($order, $payment_method, $status);
    commerce_order_status_update($order, 'canceled');
    return drupal_set_message(t('Thank you for shopping with us.However,the transaction has been declined.'));
    // Here you need to put in the routines for a failed.
    // Transaction such as sending an email to customer.
    // Setting database status etc etc.
  }
  else {
    watchdog('commerce_transactworld', $message, NULL, WATCHDOG_ERROR);
    return drupal_set_message(t('Security Error. Illegal access detected. We will store your IP address.'), ERROR);
  }
}
/**
 * transactworld finish payment
 */
function commerce_transactworld_transaction($order, $payment_method, $order_status) {
  $wrapper = entity_metadata_wrapper('commerce_order', $order);
  $currency = $wrapper->commerce_order_total->currency_code->value();
  $amount = $wrapper->commerce_order_total->amount->value();
  $transaction = commerce_payment_transaction_new('commerce_transactworld', $order->order_id);
  $transaction->instance_id = isset($payment_method['instance_id']) ? $payment_method['instance_id'] : '';
  $transaction->amount = $amount;
  $transaction->currency_code = $currency;
  // Succeessful.
  if($order_status === "Y") {
    $transaction->remote_status = t('Success');
    $transaction->message = t('Payment received at') . ' ' . date("d-m-Y H:i:s", REQUEST_TIME);
    $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
  }
  elseif($order_status === "P"){
    // Batch process - Aborted orders.
    $transaction->remote_status = t('Aborted');
    $transaction->message = t('Payment pending at') . ' ' . date("d-m-Y H:i:s", REQUEST_TIME);
    $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
  }
  elseif($order_status === "N"){
    // Failed transaction.
    $transaction->remote_status = t('Failure');
    $transaction->message = t('Payment failed at') . ' ' . date("d-m-Y H:i:s", REQUEST_TIME);
    $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
  }
  commerce_payment_transaction_save($transaction);
}

/**
 * Get checksum.
 */
function _commerce_transactworld_encrypt($plain_text, $key) {
  $secret_key = _commerce_transactworld_hextobin(md5($key));
  $init_vector = pack("C*", 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f);
  $open_mode = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', 'cbc', '');
  $block_size = mcrypt_get_block_size(MCRYPT_RIJNDAEL_128, 'cbc');
  $plain_pad = _commerce_transactworld_pkcs5_pad($plain_text, $block_size);
  if (mcrypt_generic_init($open_mode, $secret_key, $init_vector) != -1) {
    $encrypted_text = mcrypt_generic($open_mode, $plain_pad);
    mcrypt_generic_deinit($open_mode);
  }
  return bin2hex($encrypted_text);
 }

/**
 * Get checksum.
 */
function _commerce_transactworld_decrypt($encrypted_text, $key) {
  $secret_key = _commerce_transactworld_hextobin(md5($key));
  $init_vector = pack("C*", 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f);
  $encrypted_text = _commerce_transactworld_hextobin($encrypted_text);
  $open_mode = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', 'cbc', '');
  mcrypt_generic_init($open_mode, $secret_key, $init_vector);
  $decrypted_text = mdecrypt_generic($open_mode, $encrypted_text);
  $decrypted_text = rtrim($decrypted_text, "\0");
  mcrypt_generic_deinit($open_mode);
  return $decrypted_text;
 }

function _commerce_transactworld_pkcs5_pad($plain_text, $block_size) {
  $pad = $block_size - (strlen($plain_text) % $block_size);
  return $plain_text . str_repeat(chr($pad), $pad);
 }
/**
 * Create helper function called _commerce_transactworld_leftshift.
 */
function _commerce_transactworld_hextobin($hex_string) {
  $length = strlen($hex_string);
  $bin_string = '';
  $count = 0;
  while($count < $length) {
    $sub_string = substr($hex_string, $count, 2);
    $packed_string = pack("H*", $sub_string);
    if ($count == 0) {
      $bin_string = $packed_string;
    }
    else {
      $bin_string .= $packed_string;
    }
    $count += 2;
  }
  return $bin_string;
}
/**
 * Returns transactworld icon image location.
 */
function _commerce_transactworld_icons() {
  $variable = array(
    'path' => drupal_get_path('module', 'commerce_transactworld') . '/images/' . 'transactworld_home_logo.png',
    'title' => 'transactworld',
    'alt' => 'transactworld',
    'attributes' => array(
      'class' => array('commerce-transactworld-icon'),
    ),
  );
  return theme('image', $variable);
}
